supportLabel: Support

supportComment: >
  Hey @{issue-author}, we use the issue tracker exclusively for bug reports and feature requests.
  However, this issue appears to be a support request.
  Please use our **[Discord](https://discord.gg/A8TP9JY)** server to get help.

close: true
lock: false
setLockReason: true
