modLoader="javafml" 
loaderVersion="[30,)"
issueTrackerURL="https://github.com/owmii/powah/issues"

[[mods]]
modId="powah"
version="${file.jarVersion}"
#updateJSONURL="https://raw.githubusercontent.com/owmii/powah/1.15/update.json"
displayName="Powah"
displayURL="https://www.curseforge.com/minecraft/mc-mods/powah"
authors="owmii"
description='''
Various ways to generate, store and transmit FE power.
'''

[[dependencies.powah]]
    modId="lollipop"
    mandatory=true
    versionRange="[0.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.powah]]
    modId="forge"
    mandatory=true
    versionRange="[30.0.38,)"
    ordering="NONE"
    side="BOTH"